using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using WebWhatsAppClone.DataBase.Entities;

namespace WebWhatsAppClone.DataBase.Configurations
{
    public class SubRegionConfiguration : IEntityTypeConfiguration<SubRegion>
    {
        public void Configure(EntityTypeBuilder<SubRegion> builder)
        {
            builder.HasKey((sr) => sr.id);
            builder.HasOne<Region>((sr) => sr.region)
            .WithMany((r) => r.sub_regions)
            .HasForeignKey((sr) => sr.region_id);

            builder.HasData(
                new SubRegion
                {
                    id = Guid.Parse("11000000-0000-0000-0000-000000000001"),
                    key = "maghreb",
                    label = "Maghreb",
                    name = "Maghreb",
                    code = "MAG",
                    geo_code = "015-1",
                    area_km2 = 4700000,
                    population = 104000000,
                    number_of_countries = 4,
                    largest_country = "Algeria",
                    smallest_country = "Tunisia",
                    most_populous_country = "Algeria",
                    population_density = 22.1,
                    description = "Maghreb includes Morocco, Algeria, Tunisia, and Libya.",
                    region_id = Guid.Parse("10000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("11000000-0000-0000-0000-000000000002"),
                    key = "nile_valley",
                    label = "Nile Valley",
                    name = "Nile Valley",
                    code = "NIL",
                    geo_code = "015-2",
                    area_km2 = 2391800,
                    population = 142000000,
                    number_of_countries = 2,
                    largest_country = "Sudan",
                    smallest_country = "Egypt",
                    most_populous_country = "Egypt",
                    population_density = 59.3,
                    description = "Nile Valley includes Egypt and Sudan.",
                    region_id = Guid.Parse("10000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("11000000-0000-0000-0000-000000000003"),
                    key = "upper_guinea",
                    label = "Upper Guinea",
                    name = "Upper Guinea",
                    code = "UPG",
                    geo_code = "011-1",
                    area_km2 = 1750000,
                    population = 86000000,
                    number_of_countries = 6,
                    largest_country = "Mali",
                    smallest_country = "Guinea-Bissau",
                    most_populous_country = "Guinea",
                    population_density = 49.1,
                    description = "Upper Guinea includes Mali, Guinea, Guinea-Bissau, Sierra Leone, Liberia, and Côte d'Ivoire.",
                    region_id = Guid.Parse("10000000-0000-0000-0000-000000000002"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("11000000-0000-0000-0000-000000000004"),
                    key = "lower_guinea",
                    label = "Lower Guinea",
                    name = "Lower Guinea",
                    code = "LOG",
                    geo_code = "011-2",
                    area_km2 = 900000,
                    population = 97000000,
                    number_of_countries = 4,
                    largest_country = "Nigeria",
                    smallest_country = "Benin",
                    most_populous_country = "Nigeria",
                    population_density = 107.8,
                    description = "Lower Guinea includes Nigeria, Ghana, Togo, and Benin.",
                    region_id = Guid.Parse("10000000-0000-0000-0000-000000000002"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("11000000-0000-0000-0000-000000000005"),
                    key = "sahel",
                    label = "Sahel",
                    name = "Sahel",
                    code = "SAH",
                    geo_code = "011-3",
                    area_km2 = 2460000,
                    population = 65000000,
                    number_of_countries = 6,
                    largest_country = "Niger",
                    smallest_country = "Gambia",
                    most_populous_country = "Burkina Faso",
                    population_density = 26.4,
                    description = "Sahel includes Niger, Burkina Faso, Chad, Mauritania, Senegal, and Gambia.",
                    region_id = Guid.Parse("10000000-0000-0000-0000-000000000002"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("11000000-0000-0000-0000-000000000006"),
                    key = "congo_basin",
                    label = "Congo Basin",
                    name = "Congo Basin",
                    code = "CGB",
                    geo_code = "017-1",
                    area_km2 = 3700000,
                    population = 120000000,
                    number_of_countries = 5,
                    largest_country = "Democratic Republic of the Congo",
                    smallest_country = "Central African Republic",
                    most_populous_country = "Democratic Republic of the Congo",
                    population_density = 32.4,
                    description = "Congo Basin includes DR Congo, Republic of the Congo, Central African Republic, Gabon, and Cameroon.",
                    region_id = Guid.Parse("10000000-0000-0000-0000-000000000003"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("11000000-0000-0000-0000-000000000007"),
                    key = "gulf_guinea_interior",
                    label = "Gulf of Guinea Interior",
                    name = "Gulf of Guinea Interior",
                    code = "GGI",
                    geo_code = "017-2",
                    area_km2 = 2700000,
                    population = 48000000,
                    number_of_countries = 4,
                    largest_country = "Chad",
                    smallest_country = "Equatorial Guinea",
                    most_populous_country = "Cameroon",
                    population_density = 17.8,
                    description = "Gulf of Guinea Interior includes Chad, Equatorial Guinea, Angola (northern), and parts of Cameroon.",
                    region_id = Guid.Parse("10000000-0000-0000-0000-000000000003"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                                new SubRegion
                                {
                                    id = Guid.Parse("11000000-0000-0000-0000-000000000008"),
                                    key = "hoa",
                                    label = "Horn of Africa",
                                    name = "Horn of Africa",
                                    code = "HOA",
                                    geo_code = "014-1",
                                    area_km2 = 2000000,
                                    population = 140000000,
                                    number_of_countries = 4,
                                    largest_country = "Ethiopia",
                                    smallest_country = "Djibouti",
                                    most_populous_country = "Ethiopia",
                                    population_density = 70.0,
                                    description = "Horn of Africa includes Ethiopia, Somalia, Eritrea, and Djibouti.",
                                    region_id = Guid.Parse("10000000-0000-0000-0000-000000000004"),
                                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                                },
                new SubRegion
                {
                    id = Guid.Parse("11000000-0000-0000-0000-000000000009"),
                    key = "glr",
                    label = "Great Lakes Region",
                    name = "Great Lakes Region",
                    code = "GLR",
                    geo_code = "014-2",
                    area_km2 = 1500000,
                    population = 120000000,
                    number_of_countries = 5,
                    largest_country = "Tanzania",
                    smallest_country = "Burundi",
                    most_populous_country = "Tanzania",
                    population_density = 80.2,
                    description = "Great Lakes Region includes Kenya, Uganda, Tanzania, Rwanda, and Burundi.",
                    region_id = Guid.Parse("10000000-0000-0000-0000-000000000004"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("11000000-0000-0000-0000-000000000010"),
                    key = "ioi",
                    label = "Indian Ocean Islands",
                    name = "Indian Ocean Islands",
                    code = "IOI",
                    geo_code = "014-3",
                    area_km2 = 670000,
                    population = 35000000,
                    number_of_countries = 7,
                    largest_country = "Madagascar",
                    smallest_country = "Seychelles",
                    most_populous_country = "Madagascar",
                    population_density = 52.2,
                    description = "Indian Ocean Islands include Madagascar, Comoros, Mauritius, Seychelles, and others.",
                    region_id = Guid.Parse("10000000-0000-0000-0000-000000000004"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                                new SubRegion
                                {
                                    id = Guid.Parse("11000000-0000-0000-0000-000000000011"),
                                    key = "kal",
                                    label = "Kalahari Region",
                                    name = "Kalahari Region",
                                    code = "KAL",
                                    geo_code = "018-1",
                                    area_km2 = 900000,
                                    population = 2000000,
                                    number_of_countries = 3,
                                    largest_country = "Botswana",
                                    smallest_country = "Namibia",
                                    most_populous_country = "Botswana",
                                    population_density = 2.2,
                                    description = "Kalahari Region covers parts of Botswana, Namibia, and South Africa.",
                                    region_id = Guid.Parse("10000000-0000-0000-0000-000000000005"),
                                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                                },
                new SubRegion
                {
                    id = Guid.Parse("11000000-0000-0000-0000-000000000012"),
                    key = "hvl",
                    label = "Highveld",
                    name = "Highveld",
                    code = "HVL",
                    geo_code = "018-2",
                    area_km2 = 300000,
                    population = 15000000,
                    number_of_countries = 1,
                    largest_country = "South Africa",
                    smallest_country = "South Africa",
                    most_populous_country = "South Africa",
                    population_density = 50,
                    description = "Highveld is a high plateau region mainly in South Africa.",
                    region_id = Guid.Parse("10000000-0000-0000-0000-000000000005"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("11000000-0000-0000-0000-000000000013"),
                    key = "cap",
                    label = "Cape Region",
                    name = "Cape Region",
                    code = "CAP",
                    geo_code = "018-3",
                    area_km2 = 400000,
                    population = 6000000,
                    number_of_countries = 1,
                    largest_country = "South Africa",
                    smallest_country = "South Africa",
                    most_populous_country = "South Africa",
                    population_density = 15,
                    description = "Cape Region includes the Western and Eastern Cape provinces of South Africa.",
                    region_id = Guid.Parse("10000000-0000-0000-0000-000000000005"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                                new SubRegion
                                {
                                    id = Guid.Parse("21000000-0000-0000-0000-000000000001"),
                                    key = "trk",
                                    label = "Turkestan",
                                    name = "Turkestan",
                                    code = "TRK",
                                    geo_code = "143-1",
                                    area_km2 = 1200000,
                                    population = 25000000,
                                    number_of_countries = 2,
                                    largest_country = "Kazakhstan",
                                    smallest_country = "Turkmenistan",
                                    most_populous_country = "Uzbekistan",
                                    population_density = 20.8,
                                    description = "Turkestan covers parts of Kazakhstan, Uzbekistan, and Turkmenistan.",
                                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000001"),
                                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                                },
                new SubRegion
                {
                    id = Guid.Parse("21000000-0000-0000-0000-000000000002"),
                    key = "frg",
                    label = "Fergana Valley",
                    name = "Fergana Valley",
                    code = "FRG",
                    geo_code = "143-2",
                    area_km2 = 22000,
                    population = 15000000,
                    number_of_countries = 3,
                    largest_country = "Uzbekistan",
                    smallest_country = "Kyrgyzstan",
                    most_populous_country = "Uzbekistan",
                    population_density = 681.8,
                    description = "Fergana Valley is a densely populated area spread across Uzbekistan, Kyrgyzstan, and Tajikistan.",
                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("21000000-0000-0000-0000-000000000003"),
                    key = "kst",
                    label = "Kazakh Steppe",
                    name = "Kazakh Steppe",
                    code = "KST",
                    geo_code = "143-3",
                    area_km2 = 1800000,
                    population = 9000000,
                    number_of_countries = 1,
                    largest_country = "Kazakhstan",
                    smallest_country = "Kazakhstan",
                    most_populous_country = "Kazakhstan",
                    population_density = 5.0,
                    description = "Kazakh Steppe is a vast flatland that dominates northern Kazakhstan.",
                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                                new SubRegion
                                {
                                    id = Guid.Parse("22000000-0000-0000-0000-000000000001"),
                                    key = "lev",
                                    label = "Levant",
                                    name = "Levant",
                                    code = "LEV",
                                    geo_code = "145-1",
                                    area_km2 = 500000,
                                    population = 72000000,
                                    number_of_countries = 5,
                                    largest_country = "Syria",
                                    smallest_country = "Palestine",
                                    most_populous_country = "Syria",
                                    population_density = 144.0,
                                    description = "Levant covers Lebanon, Syria, Jordan, Palestine, and Israel.",
                                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000002"),
                                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                                },
                new SubRegion
                {
                    id = Guid.Parse("22000000-0000-0000-0000-000000000002"),
                    key = "arp",
                    label = "Arabian Peninsula",
                    name = "Arabian Peninsula",
                    code = "ARP",
                    geo_code = "145-2",
                    area_km2 = 3300000,
                    population = 87000000,
                    number_of_countries = 7,
                    largest_country = "Saudi Arabia",
                    smallest_country = "Bahrain",
                    most_populous_country = "Saudi Arabia",
                    population_density = 26.4,
                    description = "Arabian Peninsula includes Saudi Arabia, Yemen, Oman, UAE, Qatar, Kuwait, Bahrain.",
                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000002"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("22000000-0000-0000-0000-000000000003"),
                    key = "cac",
                    label = "Caucasus",
                    name = "Caucasus",
                    code = "CAC",
                    geo_code = "145-3",
                    area_km2 = 440000,
                    population = 18000000,
                    number_of_countries = 3,
                    largest_country = "Azerbaijan",
                    smallest_country = "Armenia",
                    most_populous_country = "Azerbaijan",
                    population_density = 40.9,
                    description = "Caucasus includes Georgia, Armenia, and Azerbaijan.",
                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000002"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("22000000-0000-0000-0000-000000000004"),
                    key = "mes",
                    label = "Mesopotamia",
                    name = "Mesopotamia",
                    code = "MES",
                    geo_code = "145-4",
                    area_km2 = 900000,
                    population = 45000000,
                    number_of_countries = 2,
                    largest_country = "Iraq",
                    smallest_country = "Syria",
                    most_populous_country = "Iraq",
                    population_density = 50.0,
                    description = "Mesopotamia covers Iraq and parts of Syria.",
                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000002"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                                new SubRegion
                                {
                                    id = Guid.Parse("23000000-0000-0000-0000-000000000001"),
                                    key = "ech",
                                    label = "East China",
                                    name = "East China",
                                    code = "ECH",
                                    geo_code = "030-1",
                                    area_km2 = 2000000,
                                    population = 600000000,
                                    number_of_countries = 1,
                                    largest_country = "China",
                                    smallest_country = "China",
                                    most_populous_country = "China",
                                    population_density = 300.0,
                                    description = "East China includes densely populated and economically significant eastern provinces of China.",
                                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000003"),
                                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                                },
                new SubRegion
                {
                    id = Guid.Parse("23000000-0000-0000-0000-000000000002"),
                    key = "nea",
                    label = "Northeast Asia",
                    name = "Northeast Asia",
                    code = "NEA",
                    geo_code = "030-2",
                    area_km2 = 500000,
                    population = 77000000,
                    number_of_countries = 2,
                    largest_country = "South Korea",
                    smallest_country = "North Korea",
                    most_populous_country = "South Korea",
                    population_density = 154.0,
                    description = "Northeast Asia refers to the Korean Peninsula, comprising North and South Korea.",
                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000003"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("23000000-0000-0000-0000-000000000003"),
                    key = "man",
                    label = "Manchuria",
                    name = "Manchuria",
                    code = "MAN",
                    geo_code = "030-3",
                    area_km2 = 800000,
                    population = 105000000,
                    number_of_countries = 1,
                    largest_country = "China",
                    smallest_country = "China",
                    most_populous_country = "China",
                    population_density = 131.3,
                    description = "Manchuria is a historical region in Northeast China, includes Liaoning, Jilin, Heilongjiang.",
                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000003"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("23000000-0000-0000-0000-000000000004"),
                    key = "jap",
                    label = "Japanese Archipelago",
                    name = "Japanese Archipelago",
                    code = "JAP",
                    geo_code = "030-4",
                    area_km2 = 378000,
                    population = 125000000,
                    number_of_countries = 1,
                    largest_country = "Japan",
                    smallest_country = "Japan",
                    most_populous_country = "Japan",
                    population_density = 330.7,
                    description = "Japanese Archipelago includes all major islands of Japan: Honshu, Hokkaido, Kyushu, Shikoku.",
                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000003"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                                new SubRegion
                                {
                                    id = Guid.Parse("24000000-0000-0000-0000-000000000001"),
                                    key = "msea",
                                    label = "Mainland Southeast Asia",
                                    name = "Mainland Southeast Asia (Indochina)",
                                    code = "MSEA",
                                    geo_code = "035-1",
                                    area_km2 = 2300000,
                                    population = 250000000,
                                    number_of_countries = 5,
                                    largest_country = "Myanmar",
                                    smallest_country = "Laos",
                                    most_populous_country = "Vietnam",
                                    population_density = 108.7,
                                    description = "Includes Vietnam, Laos, Cambodia, Thailand, and Myanmar. Also known as Indochina.",
                                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000004"),
                                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                                },
                new SubRegion
                {
                    id = Guid.Parse("24000000-0000-0000-0000-000000000002"),
                    key = "isea",
                    label = "Maritime Southeast Asia",
                    name = "Maritime Southeast Asia (Insular)",
                    code = "ISEA",
                    geo_code = "035-2",
                    area_km2 = 2190000,
                    population = 440000000,
                    number_of_countries = 5,
                    largest_country = "Indonesia",
                    smallest_country = "Brunei",
                    most_populous_country = "Indonesia",
                    population_density = 200.9,
                    description = "Includes Indonesia, Philippines, Malaysia, Singapore, and Brunei. Also known as Insular Southeast Asia.",
                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000004"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                                new SubRegion
                                {
                                    id = Guid.Parse("25000000-0000-0000-0000-000000000001"),
                                    key = "isc",
                                    label = "Indian Subcontinent",
                                    name = "Indian Subcontinent",
                                    code = "ISC",
                                    geo_code = "034-1",
                                    area_km2 = 4500000,
                                    population = 1800000000,
                                    number_of_countries = 7,
                                    largest_country = "India",
                                    smallest_country = "Bhutan",
                                    most_populous_country = "India",
                                    population_density = 400.2,
                                    description = "Includes India, Pakistan, Bangladesh, Nepal, Bhutan, and surrounding areas.",
                                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000005"),
                                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                                },
                new SubRegion
                {
                    id = Guid.Parse("25000000-0000-0000-0000-000000000002"),
                    key = "igp",
                    label = "Indo-Gangetic Plain",
                    name = "Indo-Gangetic Plain",
                    code = "IGP",
                    geo_code = "034-2",
                    area_km2 = 1000000,
                    population = 700000000,
                    number_of_countries = 3,
                    largest_country = "India",
                    smallest_country = "Nepal",
                    most_populous_country = "India",
                    population_density = 700.0,
                    description = "A large and fertile plain encompassing northern India, parts of Pakistan, and Nepal.",
                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000005"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("25000000-0000-0000-0000-000000000003"),
                    key = "himalaya",
                    label = "Himalayan Region",
                    name = "Himalayan Region",
                    code = "HIM",
                    geo_code = "034-3",
                    area_km2 = 595000,
                    population = 60000000,
                    number_of_countries = 4,
                    largest_country = "India",
                    smallest_country = "Bhutan",
                    most_populous_country = "India",
                    population_density = 100.8,
                    description = "Mountainous region including parts of India, Nepal, Bhutan, and China.",
                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000005"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("25000000-0000-0000-0000-000000000004"),
                    key = "dp",
                    label = "Deccan Plateau",
                    name = "Deccan Plateau",
                    code = "DPL",
                    geo_code = "034-4",
                    area_km2 = 1500000,
                    population = 300000000,
                    number_of_countries = 1,
                    largest_country = "India",
                    smallest_country = "India",
                    most_populous_country = "India",
                    population_density = 200.3,
                    description = "A large plateau in southern India, known for its dry and elevated terrain.",
                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000005"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("25000000-0000-0000-0000-000000000005"),
                    key = "slz",
                    label = "Sri Lankan Zone",
                    name = "Sri Lankan Zone",
                    code = "SLZ",
                    geo_code = "034-5",
                    area_km2 = 65610,
                    population = 22000000,
                    number_of_countries = 1,
                    largest_country = "Sri Lanka",
                    smallest_country = "Sri Lanka",
                    most_populous_country = "Sri Lanka",
                    population_density = 335.5,
                    description = "Island nation south of India. Distinct ecology and culture.",
                    region_id = Guid.Parse("20000000-0000-0000-0000-000000000005"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("30010000-0000-0000-0000-000000000001"),
                    key = "fns",
                    label = "Fennoscandia",
                    name = "Fennoscandia",
                    code = "FNS",
                    geo_code = "154-1",
                    area_km2 = 1300000,
                    population = 27000000,
                    number_of_countries = 3,
                    largest_country = "Sweden",
                    smallest_country = "Norway",
                    most_populous_country = "Sweden",
                    population_density = 20.8,
                    description = "Geological region comprising Norway, Sweden, Finland, and parts of Russia.",
                    region_id = Guid.Parse("30000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("30010000-0000-0000-0000-000000000002"),
                    key = "bri",
                    label = "British Isles",
                    name = "British Isles",
                    code = "BRI",
                    geo_code = "154-2",
                    area_km2 = 315000,
                    population = 70000000,
                    number_of_countries = 2,
                    largest_country = "United Kingdom",
                    smallest_country = "Ireland",
                    most_populous_country = "United Kingdom",
                    population_density = 222.2,
                    description = "Group of islands including Great Britain, Ireland and surrounding isles.",
                    region_id = Guid.Parse("30000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("30010000-0000-0000-0000-000000000003"),
                    key = "bal",
                    label = "Baltic States",
                    name = "Baltic States",
                    code = "BAL",
                    geo_code = "154-3",
                    area_km2 = 175000,
                    population = 6000000,
                    number_of_countries = 3,
                    largest_country = "Lithuania",
                    smallest_country = "Estonia",
                    most_populous_country = "Lithuania",
                    population_density = 34.2,
                    description = "Includes Estonia, Latvia, and Lithuania along the eastern Baltic Sea.",
                    region_id = Guid.Parse("30000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("30020000-0000-0000-0000-000000000001"),
                    key = "balk",
                    label = "Balkans",
                    name = "Balkans",
                    code = "BALK",
                    geo_code = "039-1",
                    area_km2 = 550000,
                    population = 55000000,
                    number_of_countries = 12,
                    largest_country = "Romania",
                    smallest_country = "Montenegro",
                    most_populous_country = "Romania",
                    population_density = 100.0,
                    description = "Southeastern Europe including countries on the Balkan Peninsula.",
                    region_id = Guid.Parse("30000000-0000-0000-0000-000000000002"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("30020000-0000-0000-0000-000000000002"),
                    key = "iber",
                    label = "Iberian Peninsula",
                    name = "Iberian Peninsula",
                    code = "IBER",
                    geo_code = "039-2",
                    area_km2 = 582000,
                    population = 60000000,
                    number_of_countries = 3,
                    largest_country = "Spain",
                    smallest_country = "Andorra",
                    most_populous_country = "Spain",
                    population_density = 103.1,
                    description = "Includes Spain, Portugal, and Andorra.",
                    region_id = Guid.Parse("30000000-0000-0000-0000-000000000002"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("30020000-0000-0000-0000-000000000003"),
                    key = "ital",
                    label = "Italian Peninsula",
                    name = "Italian Peninsula",
                    code = "ITAL",
                    geo_code = "039-3",
                    area_km2 = 301000,
                    population = 60000000,
                    number_of_countries = 3,
                    largest_country = "Italy",
                    smallest_country = "San Marino",
                    most_populous_country = "Italy",
                    population_density = 199.3,
                    description = "Geographic region including Italy, San Marino and Vatican City.",
                    region_id = Guid.Parse("30000000-0000-0000-0000-000000000002"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("30030000-0000-0000-0000-000000000001"),
                    key = "bnx",
                    label = "Benelux",
                    name = "Benelux",
                    code = "BNX",
                    geo_code = "155-1",
                    area_km2 = 75000,
                    population = 30000000,
                    number_of_countries = 3,
                    largest_country = "Belgium",
                    smallest_country = "Luxembourg",
                    most_populous_country = "Netherlands",
                    population_density = 400.1,
                    description = "Economic union of Belgium, Netherlands, and Luxembourg.",
                    region_id = Guid.Parse("30000000-0000-0000-0000-000000000003"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("30030000-0000-0000-0000-000000000002"),
                    key = "alp",
                    label = "Alpine Region",
                    name = "Alpine Region",
                    code = "ALP",
                    geo_code = "155-2",
                    area_km2 = 190000,
                    population = 15000000,
                    number_of_countries = 5,
                    largest_country = "France",
                    smallest_country = "Liechtenstein",
                    most_populous_country = "Switzerland",
                    population_density = 78.9,
                    description = "Region around the Alps including Switzerland, Austria, and others.",
                    region_id = Guid.Parse("30000000-0000-0000-0000-000000000003"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("30040000-0000-0000-0000-000000000001"),
                    key = "esl",
                    label = "East Slavic",
                    name = "East Slavic",
                    code = "ESL",
                    geo_code = "151-1",
                    area_km2 = 12500000,
                    population = 240000000,
                    number_of_countries = 3,
                    largest_country = "Russia",
                    smallest_country = "Belarus",
                    most_populous_country = "Russia",
                    population_density = 19.2,
                    description = "Includes Russia, Ukraine, and Belarus - East Slavic speaking nations.",
                    region_id = Guid.Parse("30000000-0000-0000-0000-000000000004"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("30040000-0000-0000-0000-000000000002"),
                    key = "carp",
                    label = "Carpathian Region",
                    name = "Carpathian Region",
                    code = "CARP",
                    geo_code = "151-2",
                    area_km2 = 370000,
                    population = 38000000,
                    number_of_countries = 5,
                    largest_country = "Poland",
                    smallest_country = "Slovakia",
                    most_populous_country = "Poland",
                    population_density = 102.5,
                    description = "Region around the Carpathian Mountains: Slovakia, Romania, Ukraine, etc.",
                    region_id = Guid.Parse("30000000-0000-0000-0000-000000000004"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("40010000-0000-0000-0000-000000000001"),
                    key = "ang",
                    label = "Anglo-America",
                    name = "Anglo-America",
                    code = "ANG",
                    geo_code = "021-1",
                    area_km2 = 19000000,
                    population = 330000000,
                    number_of_countries = 2,
                    largest_country = "Canada",
                    smallest_country = "USA",
                    most_populous_country = "USA",
                    population_density = 17.4,
                    description = "English-speaking part of North America: Canada and the United States.",
                    region_id = Guid.Parse("40000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("40010000-0000-0000-0000-000000000002"),
                    key = "fra",
                    label = "French America",
                    name = "French America",
                    code = "FRA",
                    geo_code = "021-2",
                    area_km2 = 1500000,
                    population = 8000000,
                    number_of_countries = 1,
                    largest_country = "Canada",
                    smallest_country = "Canada",
                    most_populous_country = "Canada",
                    population_density = 5.3,
                    description = "French-speaking regions in North America, especially Quebec.",
                    region_id = Guid.Parse("40000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("40020000-0000-0000-0000-000000000001"),
                    key = "ist",
                    label = "Isthmus Subregion",
                    name = "Isthmus Subregion",
                    code = "IST",
                    geo_code = "013-1",
                    area_km2 = 523000,
                    population = 180000000,
                    number_of_countries = 7,
                    largest_country = "Nicaragua",
                    smallest_country = "Belize",
                    most_populous_country = "Guatemala",
                    population_density = 343.0,
                    description = "Connects North and South America through countries like Panama and Costa Rica.",
                    region_id = Guid.Parse("40000000-0000-0000-0000-000000000002"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("40030000-0000-0000-0000-000000000001"),
                    key = "gai",
                    label = "Greater Antilles",
                    name = "Greater Antilles",
                    code = "GAI",
                    geo_code = "029-1",
                    area_km2 = 207000,
                    population = 39000000,
                    number_of_countries = 5,
                    largest_country = "Cuba",
                    smallest_country = "Jamaica",
                    most_populous_country = "Cuba",
                    population_density = 188.4,
                    description = "Main islands of the Caribbean including Cuba, Jamaica, Hispaniola, and Puerto Rico.",
                    region_id = Guid.Parse("40000000-0000-0000-0000-000000000003"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("40030000-0000-0000-0000-000000000002"),
                    key = "lai",
                    label = "Lesser Antilles",
                    name = "Lesser Antilles",
                    code = "LAI",
                    geo_code = "029-2",
                    area_km2 = 15000,
                    population = 4000000,
                    number_of_countries = 9,
                    largest_country = "Trinidad and Tobago",
                    smallest_country = "Saint Kitts and Nevis",
                    most_populous_country = "Trinidad and Tobago",
                    population_density = 266.7,
                    description = "Smaller islands including Grenada, Saint Lucia, Dominica, and others.",
                    region_id = Guid.Parse("40000000-0000-0000-0000-000000000003"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("40030000-0000-0000-0000-000000000003"),
                    key = "lee",
                    label = "Leeward Islands",
                    name = "Leeward Islands",
                    code = "LEE",
                    geo_code = "029-3",
                    area_km2 = 10500,
                    population = 1200000,
                    number_of_countries = 6,
                    largest_country = "Antigua and Barbuda",
                    smallest_country = "Montserrat",
                    most_populous_country = "Antigua and Barbuda",
                    population_density = 114.3,
                    description = "Northern islands of the Lesser Antilles.",
                    region_id = Guid.Parse("40000000-0000-0000-0000-000000000003"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("40030000-0000-0000-0000-000000000004"),
                    key = "win",
                    label = "Windward Islands",
                    name = "Windward Islands",
                    code = "WIN",
                    geo_code = "029-4",
                    area_km2 = 12000,
                    population = 1800000,
                    number_of_countries = 5,
                    largest_country = "Saint Lucia",
                    smallest_country = "Grenada",
                    most_populous_country = "Saint Lucia",
                    population_density = 150.0,
                    description = "Southern islands of the Lesser Antilles.",
                    region_id = Guid.Parse("40000000-0000-0000-0000-000000000003"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("50010000-0000-0000-0000-000000000001"),
                    key = "and",
                    label = "Andean States",
                    name = "Andean States",
                    code = "AND",
                    geo_code = "005-1",
                    area_km2 = 4900000,
                    population = 120000000,
                    number_of_countries = 5,
                    largest_country = "Peru",
                    smallest_country = "Ecuador",
                    most_populous_country = "Colombia",
                    population_density = 24.5,
                    description = "Countries along the Andes Mountains: Colombia, Ecuador, Peru, Bolivia, and Chile.",
                    region_id = Guid.Parse("50000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("50010000-0000-0000-0000-000000000002"),
                    key = "gui",
                    label = "Guianas",
                    name = "Guianas",
                    code = "GUI",
                    geo_code = "005-2",
                    area_km2 = 500000,
                    population = 2000000,
                    number_of_countries = 3,
                    largest_country = "Guyana",
                    smallest_country = "Suriname",
                    most_populous_country = "Guyana",
                    population_density = 4.0,
                    description = "Eastern coastal region of northern South America: Guyana, Suriname, French Guiana.",
                    region_id = Guid.Parse("50000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("50010000-0000-0000-0000-000000000003"),
                    key = "soc",
                    label = "Southern Cone",
                    name = "Southern Cone",
                    code = "SOC",
                    geo_code = "005-3",
                    area_km2 = 7100000,
                    population = 190000000,
                    number_of_countries = 4,
                    largest_country = "Argentina",
                    smallest_country = "Uruguay",
                    most_populous_country = "Argentina",
                    population_density = 26.7,
                    description = "Southernmost part of South America including Argentina, Chile, Paraguay, Uruguay.",
                    region_id = Guid.Parse("50000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("50010000-0000-0000-0000-000000000004"),
                    key = "bhl",
                    label = "Brazilian Highlands",
                    name = "Brazilian Highlands",
                    code = "BHL",
                    geo_code = "005-4",
                    area_km2 = 5800000,
                    population = 120000000,
                    number_of_countries = 1,
                    largest_country = "Brazil",
                    smallest_country = "Brazil",
                    most_populous_country = "Brazil",
                    population_density = 20.7,
                    description = "A vast region of eastern, central and southern Brazil.",
                    region_id = Guid.Parse("50000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("50010000-0000-0000-0000-000000000005"),
                    key = "amb",
                    label = "Amazon Basin",
                    name = "Amazon Basin",
                    code = "AMB",
                    geo_code = "005-5",
                    area_km2 = 7000000,
                    population = 34000000,
                    number_of_countries = 9,
                    largest_country = "Brazil",
                    smallest_country = "Ecuador",
                    most_populous_country = "Brazil",
                    population_density = 4.8,
                    description = "Tropical rainforest region covering much of northern South America.",
                    region_id = Guid.Parse("50000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("60010000-0000-0000-0000-000000000001"),
                    key = "eaus",
                    label = "Eastern Australia",
                    name = "Eastern Australia",
                    code = "EAUS",
                    geo_code = "053-1",
                    area_km2 = 4000000,
                    population = 20000000,
                    number_of_countries = 1,
                    largest_country = "Australia",
                    smallest_country = "Australia",
                    most_populous_country = "Australia",
                    population_density = 5.0,
                    description = "Eastern part of Australia including major cities like Sydney and Brisbane.",
                    region_id = Guid.Parse("60000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("60010000-0000-0000-0000-000000000002"),
                    key = "waus",
                    label = "Western Australia",
                    name = "Western Australia",
                    code = "WAUS",
                    geo_code = "053-2",
                    area_km2 = 2800000,
                    population = 2700000,
                    number_of_countries = 1,
                    largest_country = "Australia",
                    smallest_country = "Australia",
                    most_populous_country = "Australia",
                    population_density = 1.0,
                    description = "Western half of Australia with sparse population and large mining areas.",
                    region_id = Guid.Parse("60000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("60010000-0000-0000-0000-000000000003"),
                    key = "nzl",
                    label = "New Zealand",
                    name = "New Zealand",
                    code = "NZL",
                    geo_code = "053-3",
                    area_km2 = 270000,
                    population = 5000000,
                    number_of_countries = 1,
                    largest_country = "New Zealand",
                    smallest_country = "New Zealand",
                    most_populous_country = "New Zealand",
                    population_density = 18.5,
                    description = "North Island and South Island of New Zealand.",
                    region_id = Guid.Parse("60000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("60020000-0000-0000-0000-000000000001"),
                    key = "bis",
                    label = "Bismarck Archipelago",
                    name = "Bismarck Archipelago",
                    code = "BIS",
                    geo_code = "054-1",
                    area_km2 = 50000,
                    population = 1200000,
                    number_of_countries = 1,
                    largest_country = "Papua New Guinea",
                    smallest_country = "Papua New Guinea",
                    most_populous_country = "Papua New Guinea",
                    population_density = 24.0,
                    description = "Group of islands northeast of Papua New Guinea.",
                    region_id = Guid.Parse("60000000-0000-0000-0000-000000000002"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("60020000-0000-0000-0000-000000000002"),
                    key = "sol",
                    label = "Solomon Islands Arc",
                    name = "Solomon Islands Arc",
                    code = "SOL",
                    geo_code = "054-2",
                    area_km2 = 28000,
                    population = 700000,
                    number_of_countries = 1,
                    largest_country = "Solomon Islands",
                    smallest_country = "Solomon Islands",
                    most_populous_country = "Solomon Islands",
                    population_density = 25.0,
                    description = "Arc-shaped chain of volcanic islands in Melanesia.",
                    region_id = Guid.Parse("60000000-0000-0000-0000-000000000002"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("60030000-0000-0000-0000-000000000001"),
                    key = "car",
                    label = "Caroline Islands",
                    name = "Caroline Islands",
                    code = "CAR",
                    geo_code = "057-1",
                    area_km2 = 1100,
                    population = 500000,
                    number_of_countries = 3,
                    largest_country = "Federated States of Micronesia",
                    smallest_country = "Nauru",
                    most_populous_country = "FSM",
                    population_density = 450,
                    description = "Group of small islands scattered across western Pacific.",
                    region_id = Guid.Parse("60000000-0000-0000-0000-000000000003"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("60030000-0000-0000-0000-000000000002"),
                    key = "mar",
                    label = "Marshall Islands",
                    name = "Marshall Islands",
                    code = "MAR",
                    geo_code = "057-2",
                    area_km2 = 180,
                    population = 60000,
                    number_of_countries = 1,
                    largest_country = "Marshall Islands",
                    smallest_country = "Marshall Islands",
                    most_populous_country = "Marshall Islands",
                    population_density = 330.0,
                    description = "Low-lying islands and atolls in central Pacific Ocean.",
                    region_id = Guid.Parse("60000000-0000-0000-0000-000000000003"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("60030000-0000-0000-0000-000000000003"),
                    key = "mai",
                    label = "Mariana Islands",
                    name = "Mariana Islands",
                    code = "MAI",
                    geo_code = "057-3",
                    area_km2 = 1000,
                    population = 200000,
                    number_of_countries = 1,
                    largest_country = "Guam",
                    smallest_country = "Northern Mariana Islands",
                    most_populous_country = "Guam",
                    population_density = 200.0,
                    description = "Volcanic archipelago in western Pacific Ocean.",
                    region_id = Guid.Parse("60000000-0000-0000-0000-000000000003"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("60040000-0000-0000-0000-000000000001"),
                    key = "sam",
                    label = "Samoan Islands",
                    name = "Samoan Islands",
                    code = "SAM",
                    geo_code = "061-1",
                    area_km2 = 3000,
                    population = 250000,
                    number_of_countries = 2,
                    largest_country = "Samoa",
                    smallest_country = "American Samoa",
                    most_populous_country = "Samoa",
                    population_density = 83.3,
                    description = "Island group in Polynesia split between independent Samoa and American Samoa.",
                    region_id = Guid.Parse("60000000-0000-0000-0000-000000000004"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("60040000-0000-0000-0000-000000000002"),
                    key = "soc",
                    label = "Society Islands",
                    name = "Society Islands",
                    code = "SOC",
                    geo_code = "061-2",
                    area_km2 = 1600,
                    population = 280000,
                    number_of_countries = 1,
                    largest_country = "French Polynesia",
                    smallest_country = "French Polynesia",
                    most_populous_country = "French Polynesia",
                    population_density = 175.0,
                    description = "Major island group in French Polynesia including Tahiti.",
                    region_id = Guid.Parse("60000000-0000-0000-0000-000000000004"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("60040000-0000-0000-0000-000000000003"),
                    key = "marq",
                    label = "Marquesas",
                    name = "Marquesas",
                    code = "MARQ",
                    geo_code = "061-3",
                    area_km2 = 1050,
                    population = 9000,
                    number_of_countries = 1,
                    largest_country = "French Polynesia",
                    smallest_country = "French Polynesia",
                    most_populous_country = "French Polynesia",
                    population_density = 8.6,
                    description = "Isolated volcanic island group in northern French Polynesia.",
                    region_id = Guid.Parse("60000000-0000-0000-0000-000000000004"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("70010000-0000-0000-0000-000000000001"),
                    key = "east_ant",
                    label = "East Antarctica",
                    name = "East Antarctica",
                    code = "EANT",
                    geo_code = "010-1",
                    area_km2 = 10000000,
                    population = 0,
                    number_of_countries = 0,
                    largest_country = string.Empty,
                    smallest_country = string.Empty,
                    most_populous_country = string.Empty,
                    population_density = 0,
                    description = "The eastern part of Antarctica, mostly covered by ice sheets.",
                    region_id = Guid.Parse("70000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("70010000-0000-0000-0000-000000000002"),
                    key = "west_ant",
                    label = "West Antarctica",
                    name = "West Antarctica",
                    code = "WANT",
                    geo_code = "010-2",
                    area_km2 = 4000000,
                    population = 0,
                    number_of_countries = 0,
                    largest_country = string.Empty,
                    smallest_country = string.Empty,
                    most_populous_country = string.Empty,
                    population_density = 0,
                    description = "The western part of Antarctica, including the Transantarctic Mountains.",
                    region_id = Guid.Parse("70000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                },
                new SubRegion
                {
                    id = Guid.Parse("70010000-0000-0000-0000-000000000003"),
                    key = "pen_ant",
                    label = "Antarctic Peninsula",
                    name = "Antarctic Peninsula",
                    code = "PANT",
                    geo_code = "010-3",
                    area_km2 = 522000,
                    population = 0,
                    number_of_countries = 0,
                    largest_country = string.Empty,
                    smallest_country = string.Empty,
                    most_populous_country = string.Empty,
                    population_density = 0,
                    description = "The northernmost part of mainland Antarctica, extending toward South America.",
                    region_id = Guid.Parse("70000000-0000-0000-0000-000000000001"),
                    created_at = new DateTimeOffset(2025, 1, 30, 13, 45, 23, TimeSpan.Zero)
                }
            );
        }
    }
}
