// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebWhatsAppClone.DataBase;

#nullable disable

namespace WebWhatsAppClone.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250616085122_Migration-6")]
    partial class Migration6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebWhatsAppClone.DataBase.Entities.FileCategory", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("created_by")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("deleted_by")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("status_changed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("status_changed_by")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("updated_by")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("FileCategories");

                    b.HasData(
                        new
                        {
                            id = new Guid("a2c99e82-bbd5-40fe-976a-83c8f81f18f0"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Office documents such as Word, Excel, PowerPoint, PDF, and plain text files.",
                            is_active = true,
                            is_deleted = false,
                            key = "document",
                            label = "Document",
                            name = "Document Files"
                        },
                        new
                        {
                            id = new Guid("b382c1a1-0b1d-4b2c-97ad-77d5f4f43bfc"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Raster and vector image formats like JPG, PNG, GIF, BMP, SVG, and WEBP.",
                            is_active = true,
                            is_deleted = false,
                            key = "image",
                            label = "Image",
                            name = "Image Files"
                        },
                        new
                        {
                            id = new Guid("c611b50f-662a-4a3b-a6f4-8b298fa33c3f"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Multimedia files including MP4, AVI, MKV, MOV, and WEBM.",
                            is_active = true,
                            is_deleted = false,
                            key = "video",
                            label = "Video",
                            name = "Video Files"
                        },
                        new
                        {
                            id = new Guid("de5e9a6d-7ad0-4c40-a99a-1fa9876fa15f"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Sound and music formats such as MP3, WAV, FLAC, AAC, and OGG.",
                            is_active = true,
                            is_deleted = false,
                            key = "audio",
                            label = "Audio",
                            name = "Audio Files"
                        },
                        new
                        {
                            id = new Guid("60e9e9d5-11dc-44e7-b62e-5ecf399fc381"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Compressed file containers such as ZIP, RAR, 7Z, TAR, and GZ.",
                            is_active = true,
                            is_deleted = false,
                            key = "archive",
                            label = "Archive",
                            name = "Compressed Archives"
                        },
                        new
                        {
                            id = new Guid("d98fd5b0-3b70-4428-b690-d6886d2bb40d"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Files used for system settings and configuration like INI, LOG, ENV, SYS, and DLL.",
                            is_active = true,
                            is_deleted = false,
                            key = "system",
                            label = "System",
                            name = "System & Config Files"
                        },
                        new
                        {
                            id = new Guid("2f181b9f-7a31-41bb-8f17-7418f6944a7b"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Program and installer files such as EXE, MSI, APK, SH, and APP.",
                            is_active = true,
                            is_deleted = false,
                            key = "executable",
                            label = "Executable",
                            name = "Executable Files"
                        },
                        new
                        {
                            id = new Guid("70f9189f-6f15-421f-a9c9-147a0c4e40c7"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Programming and scripting languages like CS, JS, HTML, PY, PHP, TS, and JSON.",
                            is_active = true,
                            is_deleted = false,
                            key = "code",
                            label = "Code",
                            name = "Source Code Files"
                        },
                        new
                        {
                            id = new Guid("dc6c4f2a-cf57-4a4b-86b2-51e368b0d0b3"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Structured data and database files such as DB, SQL, JSON, XML, and CSV.",
                            is_active = true,
                            is_deleted = false,
                            key = "data",
                            label = "Data",
                            name = "Database & Data Files"
                        },
                        new
                        {
                            id = new Guid("8f1e33ff-1d5e-4b3e-84f8-1e922e3be39a"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Virtual and backup images including ISO, IMG, VHD, DMG, and VMDK.",
                            is_active = true,
                            is_deleted = false,
                            key = "disk-image",
                            label = "Disk Image",
                            name = "Disk Image Files"
                        },
                        new
                        {
                            id = new Guid("39b7ed68-ecb6-4c5e-b28c-eec22be967c0"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Typeface and font formats like TTF, OTF, WOFF, and WOFF2.",
                            is_active = true,
                            is_deleted = false,
                            key = "font",
                            label = "Font",
                            name = "Font Files"
                        },
                        new
                        {
                            id = new Guid("7db77137-1df3-4a42-a80e-f66e8b080be1"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Digital book formats including EPUB, MOBI, and AZW.",
                            is_active = true,
                            is_deleted = false,
                            key = "ebook",
                            label = "eBook",
                            name = "eBook Files"
                        },
                        new
                        {
                            id = new Guid("fd3ff760-5fc9-4ab2-b1f3-d110db8d1c20"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Files used in design and 3D modeling like PSD, AI, FIG, XD, DWG, and BLEND.",
                            is_active = true,
                            is_deleted = false,
                            key = "design",
                            label = "Design",
                            name = "Design & CAD Files"
                        },
                        new
                        {
                            id = new Guid("edc71b6e-cf84-44aa-b18e-7c7852a5d3a9"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Web development files such as HTML, CSS, JS, TS, and PHP.",
                            is_active = true,
                            is_deleted = false,
                            key = "web",
                            label = "Web",
                            name = "Web Files"
                        },
                        new
                        {
                            id = new Guid("eef901cf-16c7-43fc-b22e-456f8794a032"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Game assets and app data like PAK, ASSET, RES, and SAV.",
                            is_active = true,
                            is_deleted = false,
                            key = "game",
                            label = "Game",
                            name = "Game & App Resources"
                        });
                });

            modelBuilder.Entity("WebWhatsAppClone.DataBase.Entities.FileFormat", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("created_by")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("deleted_by")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("file_category_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deprecated")
                        .HasColumnType("boolean");

                    b.Property<string>("key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("maximum_size")
                        .HasColumnType("bigint");

                    b.Property<string>("mime_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("status_changed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("status_changed_by")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("updated_by")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("file_category_id");

                    b.ToTable("FileFormat");

                    b.HasData(
                        new
                        {
                            id = new Guid("d4a51598-b08b-496d-b3d1-38b35e7d8316"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Portable Document Format file format.",
                            extension = ".pdf",
                            file_category_id = new Guid("a2c99e82-bbd5-40fe-976a-83c8f81f18f0"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "pdf",
                            label = "PDF",
                            maximum_size = 16777216L,
                            mime_type = "application/pdf",
                            name = "Portable Document Format"
                        },
                        new
                        {
                            id = new Guid("8afb9733-28a8-483e-938c-221186ad11b0"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Microsoft Word 97-2003 file format.",
                            extension = ".doc",
                            file_category_id = new Guid("a2c99e82-bbd5-40fe-976a-83c8f81f18f0"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "doc",
                            label = "DOC",
                            maximum_size = 16777216L,
                            mime_type = "application/msword",
                            name = "Microsoft Word 97-2003"
                        },
                        new
                        {
                            id = new Guid("057c8055-1895-49e6-9b80-ebe78f6aabef"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Microsoft Word (Open XML) file format.",
                            extension = ".docx",
                            file_category_id = new Guid("a2c99e82-bbd5-40fe-976a-83c8f81f18f0"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "docx",
                            label = "DOCX",
                            maximum_size = 16777216L,
                            mime_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            name = "Microsoft Word (Open XML)"
                        },
                        new
                        {
                            id = new Guid("12ee019d-6102-4828-b0c3-00ef53941595"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Microsoft Excel 97-2003 file format.",
                            extension = ".xls",
                            file_category_id = new Guid("a2c99e82-bbd5-40fe-976a-83c8f81f18f0"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "xls",
                            label = "XLS",
                            maximum_size = 16777216L,
                            mime_type = "application/vnd.ms-excel",
                            name = "Microsoft Excel 97-2003"
                        },
                        new
                        {
                            id = new Guid("71d8ea38-900a-4ebc-9d13-31caf17544f1"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Microsoft Excel (Open XML) file format.",
                            extension = ".xlsx",
                            file_category_id = new Guid("a2c99e82-bbd5-40fe-976a-83c8f81f18f0"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "xlsx",
                            label = "XLSX",
                            maximum_size = 16777216L,
                            mime_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            name = "Microsoft Excel (Open XML)"
                        },
                        new
                        {
                            id = new Guid("bd7dde61-9f92-42d9-9e9e-146a773234e9"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "PowerPoint Presentation file format.",
                            extension = ".ppt",
                            file_category_id = new Guid("a2c99e82-bbd5-40fe-976a-83c8f81f18f0"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "ppt",
                            label = "PPT",
                            maximum_size = 16777216L,
                            mime_type = "application/vnd.ms-powerpoint",
                            name = "PowerPoint Presentation"
                        },
                        new
                        {
                            id = new Guid("29eeddb3-b709-4d71-bbff-21091c52bb26"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "PowerPoint (Open XML) file format.",
                            extension = ".pptx",
                            file_category_id = new Guid("a2c99e82-bbd5-40fe-976a-83c8f81f18f0"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "pptx",
                            label = "PPTX",
                            maximum_size = 16777216L,
                            mime_type = "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                            name = "PowerPoint (Open XML)"
                        },
                        new
                        {
                            id = new Guid("a10c24ce-4b9d-4007-8b92-51f8c8a615eb"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Plain Text File file format.",
                            extension = ".txt",
                            file_category_id = new Guid("a2c99e82-bbd5-40fe-976a-83c8f81f18f0"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "txt",
                            label = "TXT",
                            maximum_size = 16777216L,
                            mime_type = "text/plain",
                            name = "Plain Text File"
                        },
                        new
                        {
                            id = new Guid("36d5657d-801d-49ce-9f4b-ed7ea6192582"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Comma Separated Values file format.",
                            extension = ".csv",
                            file_category_id = new Guid("a2c99e82-bbd5-40fe-976a-83c8f81f18f0"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "csv",
                            label = "CSV",
                            maximum_size = 16777216L,
                            mime_type = "text/csv",
                            name = "Comma Separated Values"
                        },
                        new
                        {
                            id = new Guid("b05f39ac-c66e-470d-bba5-850c1b10d55f"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Rich Text Format file format.",
                            extension = ".rtf",
                            file_category_id = new Guid("a2c99e82-bbd5-40fe-976a-83c8f81f18f0"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "rtf",
                            label = "RTF",
                            maximum_size = 16777216L,
                            mime_type = "application/rtf",
                            name = "Rich Text Format"
                        },
                        new
                        {
                            id = new Guid("ebe9df37-84a6-42e4-b5bf-c097dba1c2d1"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "OpenDocument Text file format.",
                            extension = ".odt",
                            file_category_id = new Guid("a2c99e82-bbd5-40fe-976a-83c8f81f18f0"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "odt",
                            label = "ODT",
                            maximum_size = 16777216L,
                            mime_type = "application/vnd.oasis.opendocument.text",
                            name = "OpenDocument Text"
                        },
                        new
                        {
                            id = new Guid("e8b33ff5-bdb7-4bc4-8ad8-347a71200714"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 14, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Widely used compressed image format for digital photography.",
                            extension = ".jpg",
                            file_category_id = new Guid("b382c1a1-0b1d-4b2c-97ad-77d5f4f43bfc"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "jpg",
                            label = "JPG",
                            maximum_size = 16777216L,
                            mime_type = "image/jpeg",
                            name = "JPEG Image"
                        },
                        new
                        {
                            id = new Guid("fd37bba4-68d3-42f6-9bdf-c248c3d3972e"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 14, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Alternative extension for JPG image format.",
                            extension = ".jpeg",
                            file_category_id = new Guid("b382c1a1-0b1d-4b2c-97ad-77d5f4f43bfc"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "jpeg",
                            label = "JPEG",
                            maximum_size = 16777216L,
                            mime_type = "image/jpeg",
                            name = "JPEG Image"
                        },
                        new
                        {
                            id = new Guid("c93fe653-33d0-45d8-9611-2d82eb6bd087"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 14, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Lossless image format commonly used for web graphics and UI design.",
                            extension = ".png",
                            file_category_id = new Guid("b382c1a1-0b1d-4b2c-97ad-77d5f4f43bfc"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "png",
                            label = "PNG",
                            maximum_size = 16777216L,
                            mime_type = "image/png",
                            name = "Portable Network Graphics"
                        },
                        new
                        {
                            id = new Guid("62a3d8ae-81fa-4c8e-b2f6-41a2f90a7490"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 14, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Animated or static image format with limited color palette.",
                            extension = ".gif",
                            file_category_id = new Guid("b382c1a1-0b1d-4b2c-97ad-77d5f4f43bfc"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "gif",
                            label = "GIF",
                            maximum_size = 16777216L,
                            mime_type = "image/gif",
                            name = "Graphics Interchange Format"
                        },
                        new
                        {
                            id = new Guid("dbb4d630-4a41-4900-844c-d99483ac7237"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 14, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Vector-based image format for scalable graphics.",
                            extension = ".svg",
                            file_category_id = new Guid("b382c1a1-0b1d-4b2c-97ad-77d5f4f43bfc"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "svg",
                            label = "SVG",
                            maximum_size = 16777216L,
                            mime_type = "image/svg+xml",
                            name = "Scalable Vector Graphics"
                        },
                        new
                        {
                            id = new Guid("52ed76e7-1614-47be-93f7-0f4df56c9a8a"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 14, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Uncompressed raster image format mainly used in Windows systems.",
                            extension = ".bmp",
                            file_category_id = new Guid("b382c1a1-0b1d-4b2c-97ad-77d5f4f43bfc"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "bmp",
                            label = "BMP",
                            maximum_size = 16777216L,
                            mime_type = "image/bmp",
                            name = "Bitmap Image File"
                        },
                        new
                        {
                            id = new Guid("19dfb162-78e9-4b4f-9b45-2d4308ed746f"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 14, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "High-quality image format often used in publishing and scanning.",
                            extension = ".tiff",
                            file_category_id = new Guid("b382c1a1-0b1d-4b2c-97ad-77d5f4f43bfc"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "tiff",
                            label = "TIFF",
                            maximum_size = 16777216L,
                            mime_type = "image/tiff",
                            name = "Tagged Image File Format"
                        },
                        new
                        {
                            id = new Guid("04127520-7ef4-4cf1-8829-d70b7c3c0138"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 14, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Modern image format providing superior compression for web usage.",
                            extension = ".webp",
                            file_category_id = new Guid("b382c1a1-0b1d-4b2c-97ad-77d5f4f43bfc"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "webp",
                            label = "WEBP",
                            maximum_size = 16777216L,
                            mime_type = "image/webp",
                            name = "WebP Image Format"
                        },
                        new
                        {
                            id = new Guid("c05c21be-3e27-4326-92c2-f1160c8a1501"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 14, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Used to store icons in Windows applications.",
                            extension = ".ico",
                            file_category_id = new Guid("b382c1a1-0b1d-4b2c-97ad-77d5f4f43bfc"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "ico",
                            label = "ICO",
                            maximum_size = 1048576L,
                            mime_type = "image/x-icon",
                            name = "Icon File"
                        },
                        new
                        {
                            id = new Guid("40000000-0000-0000-0000-000000000001"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Standard video format for streaming and mobile.",
                            extension = ".mp4",
                            file_category_id = new Guid("c611b50f-662a-4a3b-a6f4-8b298fa33c3f"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "mp4",
                            label = "MP4",
                            maximum_size = 500000000L,
                            mime_type = "video/mp4",
                            name = "MPEG-4 Video"
                        },
                        new
                        {
                            id = new Guid("40000000-0000-0000-0000-000000000002"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Older format developed by Microsoft.",
                            extension = ".avi",
                            file_category_id = new Guid("c611b50f-662a-4a3b-a6f4-8b298fa33c3f"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "avi",
                            label = "AVI",
                            maximum_size = 2000000000L,
                            mime_type = "video/x-msvideo",
                            name = "Audio Video Interleave"
                        },
                        new
                        {
                            id = new Guid("40000000-0000-0000-0000-000000000003"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Modern container format for high-quality video.",
                            extension = ".mkv",
                            file_category_id = new Guid("c611b50f-662a-4a3b-a6f4-8b298fa33c3f"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "mkv",
                            label = "MKV",
                            maximum_size = 2000000000L,
                            mime_type = "video/x-matroska",
                            name = "Matroska Video"
                        },
                        new
                        {
                            id = new Guid("40000000-0000-0000-0000-000000000004"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Format used by Apple's QuickTime framework.",
                            extension = ".mov",
                            file_category_id = new Guid("c611b50f-662a-4a3b-a6f4-8b298fa33c3f"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "mov",
                            label = "MOV",
                            maximum_size = 1000000000L,
                            mime_type = "video/quicktime",
                            name = "Apple QuickTime Movie"
                        },
                        new
                        {
                            id = new Guid("40000000-0000-0000-0000-000000000005"),
                            created_at = new DateTimeOffset(new DateTime(2025, 5, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Open, royalty-free format designed for the web.",
                            extension = ".webm",
                            file_category_id = new Guid("c611b50f-662a-4a3b-a6f4-8b298fa33c3f"),
                            is_active = true,
                            is_deleted = false,
                            is_deprecated = false,
                            key = "webm",
                            label = "WEBM",
                            maximum_size = 500000000L,
                            mime_type = "video/webm",
                            name = "WebM Video"
                        });
                });

            modelBuilder.Entity("WebWhatsAppClone.DataBase.Entities.FileFormat", b =>
                {
                    b.HasOne("WebWhatsAppClone.DataBase.Entities.FileCategory", "file_category")
                        .WithMany("file_formats")
                        .HasForeignKey("file_category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("file_category");
                });

            modelBuilder.Entity("WebWhatsAppClone.DataBase.Entities.FileCategory", b =>
                {
                    b.Navigation("file_formats");
                });
#pragma warning restore 612, 618
        }
    }
}
