// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebWhatsAppClone.DataBase;

#nullable disable

namespace WebWhatsAppClone.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebWhatsAppClone.DataBase.Entities.FileCategory", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("created_by")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("deleted_by")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("status_changed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("status_changed_by")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("updated_by")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("FileCategories");

                    b.HasData(
                        new
                        {
                            id = new Guid("a2c99e82-bbd5-40fe-976a-83c8f81f18f0"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Office documents such as Word, Excel, PowerPoint, PDF, and plain text files.",
                            is_active = true,
                            is_deleted = false,
                            key = "document",
                            label = "Document",
                            name = "Document Files"
                        },
                        new
                        {
                            id = new Guid("b382c1a1-0b1d-4b2c-97ad-77d5f4f43bfc"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Raster and vector image formats like JPG, PNG, GIF, BMP, SVG, and WEBP.",
                            is_active = true,
                            is_deleted = false,
                            key = "image",
                            label = "Image",
                            name = "Image Files"
                        },
                        new
                        {
                            id = new Guid("c611b50f-662a-4a3b-a6f4-8b298fa33c3f"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Multimedia files including MP4, AVI, MKV, MOV, and WEBM.",
                            is_active = true,
                            is_deleted = false,
                            key = "video",
                            label = "Video",
                            name = "Video Files"
                        },
                        new
                        {
                            id = new Guid("de5e9a6d-7ad0-4c40-a99a-1fa9876fa15f"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Sound and music formats such as MP3, WAV, FLAC, AAC, and OGG.",
                            is_active = true,
                            is_deleted = false,
                            key = "audio",
                            label = "Audio",
                            name = "Audio Files"
                        },
                        new
                        {
                            id = new Guid("60e9e9d5-11dc-44e7-b62e-5ecf399fc381"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Compressed file containers such as ZIP, RAR, 7Z, TAR, and GZ.",
                            is_active = true,
                            is_deleted = false,
                            key = "archive",
                            label = "Archive",
                            name = "Compressed Archives"
                        },
                        new
                        {
                            id = new Guid("d98fd5b0-3b70-4428-b690-d6886d2bb40d"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Files used for system settings and configuration like INI, LOG, ENV, SYS, and DLL.",
                            is_active = true,
                            is_deleted = false,
                            key = "system",
                            label = "System",
                            name = "System & Config Files"
                        },
                        new
                        {
                            id = new Guid("2f181b9f-7a31-41bb-8f17-7418f6944a7b"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Program and installer files such as EXE, MSI, APK, SH, and APP.",
                            is_active = true,
                            is_deleted = false,
                            key = "executable",
                            label = "Executable",
                            name = "Executable Files"
                        },
                        new
                        {
                            id = new Guid("70f9189f-6f15-421f-a9c9-147a0c4e40c7"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Programming and scripting languages like CS, JS, HTML, PY, PHP, TS, and JSON.",
                            is_active = true,
                            is_deleted = false,
                            key = "code",
                            label = "Code",
                            name = "Source Code Files"
                        },
                        new
                        {
                            id = new Guid("dc6c4f2a-cf57-4a4b-86b2-51e368b0d0b3"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Structured data and database files such as DB, SQL, JSON, XML, and CSV.",
                            is_active = true,
                            is_deleted = false,
                            key = "data",
                            label = "Data",
                            name = "Database & Data Files"
                        },
                        new
                        {
                            id = new Guid("8f1e33ff-1d5e-4b3e-84f8-1e922e3be39a"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Virtual and backup images including ISO, IMG, VHD, DMG, and VMDK.",
                            is_active = true,
                            is_deleted = false,
                            key = "disk-image",
                            label = "Disk Image",
                            name = "Disk Image Files"
                        },
                        new
                        {
                            id = new Guid("39b7ed68-ecb6-4c5e-b28c-eec22be967c0"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Typeface and font formats like TTF, OTF, WOFF, and WOFF2.",
                            is_active = true,
                            is_deleted = false,
                            key = "font",
                            label = "Font",
                            name = "Font Files"
                        },
                        new
                        {
                            id = new Guid("7db77137-1df3-4a42-a80e-f66e8b080be1"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Digital book formats including EPUB, MOBI, and AZW.",
                            is_active = true,
                            is_deleted = false,
                            key = "ebook",
                            label = "eBook",
                            name = "eBook Files"
                        },
                        new
                        {
                            id = new Guid("fd3ff760-5fc9-4ab2-b1f3-d110db8d1c20"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Files used in design and 3D modeling like PSD, AI, FIG, XD, DWG, and BLEND.",
                            is_active = true,
                            is_deleted = false,
                            key = "design",
                            label = "Design",
                            name = "Design & CAD Files"
                        },
                        new
                        {
                            id = new Guid("edc71b6e-cf84-44aa-b18e-7c7852a5d3a9"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Web development files such as HTML, CSS, JS, TS, and PHP.",
                            is_active = true,
                            is_deleted = false,
                            key = "web",
                            label = "Web",
                            name = "Web Files"
                        },
                        new
                        {
                            id = new Guid("eef901cf-16c7-43fc-b22e-456f8794a032"),
                            created_at = new DateTimeOffset(new DateTime(2025, 3, 25, 13, 45, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Game assets and app data like PAK, ASSET, RES, and SAV.",
                            is_active = true,
                            is_deleted = false,
                            key = "game",
                            label = "Game",
                            name = "Game & App Resources"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
